name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt-get update
        sudo apt-get install -y make
        # Create virtual environment and install dependencies with a Unix-friendly path
        python -m venv venv
        source venv/bin/activate && pip install -r requirements.txt

    - name: Run server
      run: |
        # Source the virtual environment and run the server
        source venv/bin/activate
        make run &
        # Wait for the server to start
        sleep 10

    - name: Check server is running (optional)
      run: |
        # Optional step to ensure server is running, replace this with actual tests if needed
        curl http://0.0.0.0:3000
