name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: make install

    - name: Run server
      run: make run

    - name: Wait for server to start
      uses: jakejarvis/wait-action@v1
      with:
        time: '20s'

    - name: Test server is running
      run: |
        $response = Invoke-WebRequest http://localhost:3000
        if ($response.StatusCode -ne 200) {
          Write-Host "Server did not start correctly."
          exit 1
        } else {
          Write-Host "Server is running correctly."
        }
      shell: pwsh
