name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
      
    - name: Install dependencies and run make install
      run: |
        python -m pip install --upgrade pip
        # Install make if not present
        sudo apt-get update
        sudo apt-get install -y make
        # Run make install
        make install

    - name: Run server
      run: |
        make run &
        # Wait for the server to start
        sleep 10

    # Include additional steps if needed, otherwise remove these comments
    # - name: Test with pytest (if applicable)
    #   run: |
    #     source venv/bin/activate
    #     pytest
